version: '3.2'

services:
   json-server-dev:
      build: ./dev
      ports:
         - '3001:80'
      volumes:
         - '/home/g1640260/vaolo-json/dev/vaolo-db-dev.json:/data/db.json'
      image: clue/json-server

   json-server-staging:
      build: ./staging
      ports:
         - '3002:80'
      volumes:
         - '/home/g1640260/vaolo-json/staging/vaolo-db-staging.json:/data/db.json'
      image: clue/json-server
